### ISSUE TITLE
Building on OSX fails

### ISSUE THREAD

**Issue by kjyv** [robotology-playground/iDynTree-superbuild#1] opened 2016-04-14 20:00 UTC
Building on OSX with this superbuild seems pretty hard. It tries to build YARP which needs ACE, but I couldn't build that at the moment because of a MacPorts problem I suppose. It should in any case be in the dependencies. Better though I would like to disable using YARP anyway, but there doesn't seem to be an option in the superbuild (iDynTree itself has it as it seems).
Setting the flag (SKIP_ACE=ON) install gsl and commenting a line assigning a thread id that threw an error, I could continue. Disabling the ICUB dependency would also be useful as it is quite large and it also depends on ACE (and I can't build it atm...).

**Comment by traversaro** [comment] 2016-04-15 07:12
I see, tipically people on OS X install ACE throught homebrew rather then MacPorts. However the YARP-depending part of iDynTree should work fine even without ACE. Adding some option to disable the "optional" dependencies of iDynTree is rather easy. I can work on this in the plane that I have later this afternoon, I will update you. : )

**Comment by kjyv** [comment] 2016-04-15 10:16
Yeah, I figured and it is possible to build YARP without ACE but then ICUB complains about not finding ACE. Within the superbuild, I was not able to make it stop building YARP and ICUB, but I didn't go deeper into what YCM etc. does. A superbuild option would be ideal :)

**Comment by kjyv** [comment] 2016-04-18 21:20
Ok, sorry, more issues. Building is ok now, but when using the dylibs:

```
ImportError: dlopen(/Users/stefan/Desktop/IIT/iDynTree-superbuild/build/install/lib/python2.7/site-packages/_iDynTree.so, 2): Library not loaded: libtinyxml.2.6.2.dylib
  Referenced from: /Users/stefan/Desktop/IIT/iDynTree-superbuild/build/install/lib/python2.7/site-packages/_iDynTree.so
  Reason: unsafe use of relative rpath libtinyxml.2.6.2.dylib in /Users/stefan/Desktop/IIT/iDynTree-superbuild/build/install/lib/python2.7/site-packages/_iDynTree.so with restricted binary
```

which is because of relative rpath instead of absolute (since El Capitan), see here
http://stackoverflow.com/questions/31343299/mysql-improperly-configured-reason-unsafe-use-of-relative-path
Using install_name_tool on various dylibs works fine.

There is something in the Cmake documentation about setting absolute paths in the build tree and again when installing, maybe that is the way to go: https://cmake.org/Wiki/CMake_RPATH_handling.
(A bit too tired right now to look into it... :))

**Comment by traversaro** [comment] 2016-04-18 21:26
I have an expert on RPATH handling in OS X in my group, I will ask to him tomorrow morning. : D

**Comment by traversaro** [comment] 2018-06-08 09:31
Closing the issue here as the issue is tracked in https://github.com/robotology/idyntree/issues/241 .

**Closed as completed by traversaro** 2018-06-08 09:31 UTC
